=== SlicerUltrasound/SlicerUltrasound/AnnotateUltrasound/annotations.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ImageRecord (Flat frame_annotations structure)",
  "type": "object",
  "properties": {
    "SOPInstanceUID": {
      "type": "string"
    },
    "GrayscaleConversion": {
      "type": "boolean"
    },
    "mask_type": {
      "type": "string"
    },
    "angle1": {
      "type": "number"
    },
    "angle2": {
      "type": "number"
    },
    "center_rows_px": {
      "type": "integer"
    },
    "center_cols_px": {
      "type": "integer"
    },
    "radius1": {
      "type": "integer"
    },
    "radius2": {
      "type": "integer"
    },
    "image_size_rows": {
      "type": "integer"
    },
    "image_size_cols": {
      "type": "integer"
    },
    "AnnotationLabels": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "labels": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "frame_annotations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "frame_number": {
            "type": [
              "string",
              "integer"
            ]
          },
          "coordinate_space": {
            "type": "string",
            "enum": ["LPS", "RAS"],
            "default": "RAS"
          },
          "pleura_lines": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "rater": {
                  "type": "string"
                },
                "line": {
                  "type": "object",
                  "properties": {
                    "points": {
                      "type": "array",
                      "items": {
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 3,
                        "items": {
                          "type": "number"
                        }
                      }
                    }
                  },
                  "required": [
                    "points"
                  ]
                }
              },
              "required": [
                "rater",
                "line"
              ]
            }
          },
          "b_lines": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "rater": {
                  "type": "string"
                },
                "line": {
                  "type": "object",
                  "properties": {
                    "points": {
                      "type": "array",
                      "items": {
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 3,
                        "items": {
                          "type": "number"
                        }
                      }
                    }
                  },
                  "required": [
                    "points"
                  ]
                }
              },
              "required": [
                "rater",
                "line"
              ]
            }
          }
        },
        "required": [
          "frame_number",
          "pleura_lines",
          "b_lines"
        ]
      }
    }
  },
  "required": [
    "SOPInstanceUID",
    "frame_annotations"
  ]
}

=== SlicerUltrasound/SlicerUltrasound/AnnotateUltrasound/Testing/Python/test_data/9938886735_88815303.tom.json
{"frame_annotations": [{"frame_number": 0, "coordinate_space": "LPS", "pleura_lines": [{"rater": "tom", "line": {"points": [[114.66091283947797, 41.09415560232186, 0.0], [130.90843347694522, 36.14064321285015, 0.0]]}}], "b_lines": [{"rater": "tom", "line": {"points": [[127.54004505210442, 74.57989935515067, 0.0], [135.46566487525917, 72.598494399362, 0.0]]}}]}], "SOPInstanceUID": "1.3.6.1.4.1.14519.5.2.1.1188.2803.312032993605991049467050423443", "GrayscaleConversion": false, "mask_type": "fan", "angle1": 119.76707176040014, "angle2": 57.38670201615424, "center_rows_px": -157, "center_cols_px": 420, "radius1": 256, "radius2": 720, "image_size_rows": 649, "image_size_cols": 850, "AnnotationLabels": [], "labels": []}
